# Generated by Django 4.0.3 on 2022-04-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento_cancelado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data_horario']},
        ),
    ]
