# Generated by Django 4.0.3 on 2022-04-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agendamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_horario']},
        ),
    ]
